# Generated by Django 3.1 on 2020-08-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_scrapping', models.BooleanField(default=False)),
                ('is_right_email', models.BooleanField(default=False)),
                ('is_hackable', models.BooleanField(default=False)),
                ('is_hacked', models.BooleanField(default=False)),
                ('is_invalid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Instagram user',
                'verbose_name_plural': 'Instagram users',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instauser')),
            ],
            options={
                'verbose_name': 'Scrapping process',
                'verbose_name_plural': 'Scrapping processes',
                'ordering': ('created_at',),
            },
        ),
    ]
