# Generated by Django 3.1 on 2020-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='ig_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
