# Generated by Django 3.1 on 2020-08-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_instauser_ig_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='is_hackable',
        ),
        migrations.RemoveField(
            model_name='instauser',
            name='is_hacked',
        ),
        migrations.RemoveField(
            model_name='instauser',
            name='is_invalid',
        ),
        migrations.RemoveField(
            model_name='instauser',
            name='is_right_email',
        ),
        migrations.AddField(
            model_name='instauser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Invalid'), (1, "Didn't checked"), (2, 'Right email'), (3, 'Hackable'), (4, 'Hacked')], default=1),
        ),
    ]
