# Generated by Django 3.1 on 2020-08-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200822_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
