# Generated by Django 3.1 on 2020-08-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200822_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='name',
            field=models.CharField(default='qwe', max_length=100),
            preserve_default=False,
        ),
    ]
