# Generated by Django 3.1 on 2020-08-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_instauser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
