# Generated by Django 3.1 on 2020-08-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200822_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='id',
        ),
        migrations.AddField(
            model_name='instauser',
            name='subscriptions',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='api_key',
            field=models.CharField(default='qwe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='count',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='ig_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, "Didn't checked"), (1, 'Right email'), (2, 'Hackable'), (3, 'Hacked'), (4, 'Unhackable'), (5, 'Invalid')], default=0),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='subscribers',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.process')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
