# Generated by Django 3.1 on 2020-08-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200825_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='is_processed',
        ),
    ]
