# Generated by Django 3.1 on 2020-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_instauser_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
