# Generated by Django 3.1 on 2020-08-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200825_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
