# Generated by Django 3.1 on 2020-08-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_instauser_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='is_invalid_process',
            field=models.BooleanField(default=False),
        ),
    ]
