# Generated by Django 3.1 on 2020-08-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200825_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='ig_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
