# Generated by Django 3.1 on 2020-08-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200825_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Checking API'), (2, 'Creating task'), (3, 'Creating users')], default=2),
            preserve_default=False,
        ),
    ]
