# Generated by Django 3.1 on 2020-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
