# Generated by Django 3.1 on 2020-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200826_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='task',
        ),
        migrations.AddField(
            model_name='log',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
