# Generated by Django 3.1 on 2020-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_instauser_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='api_key',
            field=models.CharField(default='No', max_length=100),
            preserve_default=False,
        ),
    ]
