# Generated by Django 3.1 on 2020-08-27 07:03

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_log_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='checked_at',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
