# Generated by Django 3.1 on 2020-08-27 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20200827_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='checked_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 7, 6, 13, 426220, tzinfo=utc)),
        ),
    ]
