# Generated by Django 3.1 on 2020-08-27 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20200827_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='checked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
