# Generated by Django 3.1 on 2020-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200827_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='checked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
