# Generated by Django 3.1 on 2020-08-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200827_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributesMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.controller')),
            ],
        ),
    ]
