# Generated by Django 3.1 on 2020-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_attributesmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AttributesMap',
        ),
    ]
