# Generated by Django 3.1 on 2020-08-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20200827_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='UserChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_was', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instauser')),
            ],
        ),
    ]
