# Generated by Django 3.1 on 2020-08-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200827_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChanges',
        ),
    ]
