# Generated by Django 3.1 on 2020-08-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_delete_userchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='tid',
            field=models.CharField(default='No', max_length=20),
            preserve_default=False,
        ),
    ]
