# Generated by Django 3.1 on 2020-08-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20200827_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='api_key',
            field=models.CharField(default='No', max_length=55),
            preserve_default=False,
        ),
    ]
