# Generated by Django 3.1 on 2020-08-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_apikey_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Right email'), (2, 'Hackable'), (3, 'Hacked'), (4, 'Unhackable'), (5, 'Not interesting')]),
        ),
    ]
