# Generated by Django 3.1 on 2020-09-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200828_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
