# Generated by Django 3.1 on 2020-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200902_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Black List word',
                'verbose_name_plural': 'Black List words',
            },
        ),
    ]
