# Generated by Django 3.1 on 2020-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20200903_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ('created_at',), 'verbose_name': 'Queue', 'verbose_name_plural': 'Queue'},
        ),
        migrations.AddField(
            model_name='queue',
            name='in_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2),
        ),
    ]
