# Generated by Django 3.1 on 2020-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200904_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='group',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=2),
        ),
    ]
